Update geonode_authorize_layer.sql
Added condition based on latest revision in the geoserver-geonode-ext repo to account for anonymous user authentication where the user_name arg will be null. Without this statement, the following exception will occur:

----
ERROR [geonode.security] - Error getting results
org.postgresql.util.PSQLException: ERROR: record "user" is not assigned yet
  Detail: The tuple structure of a not-yet-assigned record is indeterminate.
  Where: SQL statement "SELECT  array_agg("groups_groupmember"."group_id")
  FROM "groups_groupmember"
  WHERE "groups_groupmember"."user_id" = "user".id"
----

The latest revision also includes an additional change that I am testing before I apply. Since the stated assumption in the commit references a specific record and id, I need to confirm that this holds true for the migrated data in v2.    
https://github.com/GeoNode/geoserver-geonode-ext/commit/32a5886eac2183f87d5924349b302f83b8d7bd65